---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[scpr-consul-haproxy-test]
      - recipe[scpr-consul-haproxy::default]
    attributes:
      consul:
        service_mode: bootstrap
  - name: haproxy15
    run_list:
      - recipe[scpr-consul-haproxy-test]
      - recipe[scpr-consul-haproxy::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_consul_haproxy:
        use_1_5: true
  - name: streammachine
    run_list:
      - recipe[scpr-consul-haproxy-test]
      - recipe[scpr-consul-haproxy::streammachine]
    attributes:
      consul:
        service_mode: bootstrap