---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[scpr-consul-haproxy::default]
    attributes:
  - name: haproxy15
    run_list:
      - recipe[scpr-consul-haproxy::default]
    attributes:
      scpr_consul_haproxy:
        use_1_5: true
